/**************************************************************************************************/
/** @file     syscalls.c
 *  @brief    Auto-generated by STM32CubeIDE
 *  @details  STM32CubeIDE Minimal System calls file
 *
 *	@section 	Detail
 *		For more information about which c-functions need which of these low-level functions please
 *		consult the Newlib libc-manual
 *
 *  @section 	Opens
 * 		fcn headers!
 */
/**************************************************************************************************/

//************************************************************************************************//
//                                            INCLUDES                                            //
//************************************************************************************************//

//Standard Library includes
#include <stdlib.h>
#include <errno.h>
#include <stdio.h>
#include <signal.h>
#include <time.h>

//SDK Includes
#include <sys/stat.h>
#include <sys/time.h>
#include <sys/times.h>


//************************************************************************************************//
//                                            VARIABLES                                           //
//************************************************************************************************//

extern int __io_putchar(int ch) __attribute__((weak));
extern int __io_getchar(void) __attribute__((weak));


char *__env[1] = {0};
char **environ = __env;

//************************************************************************************************//
//                                             FUNCTIONS                                          //
//************************************************************************************************//

/**************************************************************************************************/
/** @fcn        void initialise_monitor_handles(void)
 *  @brief      x
 *  @details    x
 */
/**************************************************************************************************/
void initialise_monitor_handles(void) {
	return;
}


/**************************************************************************************************/
/** @fcn        int _getpid(void)
 *  @brief      x
 *  @details    x
 *
 *  @section    Opens
 *      Capture return value information
 */
/**************************************************************************************************/
int _getpid(void) {
  return 1;
}

/**************************************************************************************************/
/** @fcn        int _kill(int pid, int sig)
 *  @brief      x
 *  @details    x
 *
 *  @param    [in]  (int) pid - x
 *  @param    [in]  (int) sig - x
 *
 *  @return   (int) x
 *
 *  @section    Opens
 *      Capture return value information
 */
/**************************************************************************************************/
int _kill(int pid, int sig) {

	//Locals
	(void)pid;
	(void)sig;

	errno = EINVAL;

	return -1;
}


/**************************************************************************************************/
/** @fcn        void _exit (int status)
 *  @brief      x
 *  @details    x
 *
 *  @param    [in]  (int) status - x
 */
/**************************************************************************************************/
void _exit (int status) {

  _kill(status, -1);

  for(;;); 											/* Make sure we hang here 					  */
}


/**************************************************************************************************/
/** @fcn        int _read(int file, char *ptr, int len)
 *  @brief      x
 *  @details    x
 *
 *  @param    [in]  (int)    file - x
 *  @param    [in]  (char *) ptr  - x
 *  @param    [in]  (int)    len  - x
 *
 *  @return   (int) x
 *
 *  @section    Opens
 *      Capture return value information
 */
/**************************************************************************************************/
__attribute__((weak)) int _read(int file, char *ptr, int len) {

	//Locals
	(void)file;
	int DataIdx;

	for(DataIdx = 0; DataIdx < len; DataIdx++) {
		*ptr++ = __io_getchar();
	}

	return len;
}

/**************************************************************************************************/
/** @fcn        int _write(int file, char *ptr, int len)
 *  @brief      x
 *  @details    x
 *
 *  @param    [in]  (int)    file - x
 *  @param    [in]  (char *) ptr  - x
 *  @param    [in]  (int)    len  - x
 *
 *  @return   (int) x
 *
 *  @section    Opens
 *      Capture return value information
 */
/**************************************************************************************************/
__attribute__((weak)) int _write(int file, char *ptr, int len) {

	//Locals
	(void)file;
	int DataIdx;

	for(DataIdx = 0; DataIdx < len; DataIdx++) {
		__io_putchar(*ptr++);
	}

	return len;
}

/**************************************************************************************************/
/** @fcn        int _close(int file)
 *  @brief      x
 *  @details    x
 *
 *  @param    [in]  (int) file - x
 *
 *  @return   (int) x
 *
 *  @section    Opens
 *      Capture return value information
 */
/**************************************************************************************************/
int _close(int file) {

	//Locals
	(void)file;

	return -1;
}


/**************************************************************************************************/
/** @fcn        int _fstat(int file, struct stat *st)
 *  @brief      x
 *  @details    x
 *
 *  @param    [in]  (int)           file - x
 *  @param    [in]  (struct stat *) st   - x
 *
 *  @return   (int) x
 *
 *  @section    Opens
 *      Capture return value information
 */
/**************************************************************************************************/
int _fstat(int file, struct stat *st) {

	//Locals
	(void)file;

	st->st_mode = S_IFCHR;

	return 0;
}


/**************************************************************************************************/
/** @fcn        int _isatty(int file)
 *  @brief      x
 *  @details    x
 *
 *  @param    [in]  (int) file - x
 *
 *  @return   (int) x
 *
 *  @section    Opens
 *      Capture return value information
 */
/**************************************************************************************************/
int _isatty(int file) {

	//Locals
	(void)file;

	return 1;
}

/**************************************************************************************************/
/** @fcn        int _lseek(int file, int ptr, int dir)
 *  @brief      x
 *  @details    x
 *
 *  @param    [in]  (int) file - x
 *  @param    [in]  (int) ptr  - x
 *  @param    [in]  (int) dir  - x
 *
 *  @return   (int) x
 *
 *  @section    Opens
 *      Capture return value information
 */
/**************************************************************************************************/
int _lseek(int file, int ptr, int dir) {

	//Locals
	(void)file;
	(void)ptr;
	(void)dir;

	return 0;
}


/**************************************************************************************************/
/** @fcn        int _open(char *path, int flags, ...)
 *  @brief      x
 *  @details    x
 *
 *  @param    [in]  (char *) path - x
 *  @param    [in]  (int) flags   - x
 *  @param    [in]  () ...        - x
 *
 *  @return   (int) x
 *
 *  @section    Opens
 *      Capture return value information
 */
/**************************************************************************************************/
int _open(char *path, int flags, ...) {

	//Locals
	(void)path;
	(void)flags;

	/* Pretend like we always fail */
	return -1;
}


/**************************************************************************************************/
/** @fcn        int _unlink(char *name)
 *  @brief      x
 *  @details    x
 *
 *  @param    [in]  (char *) name - x
 *
 *  @return   (int) x
 *
 *  @section    Opens
 *      Capture return value information
 */
/**************************************************************************************************/
int _wait(int *status) {

	//Locals
	(void)status;

	errno = ECHILD;

	return -1;
}


/**************************************************************************************************/
/** @fcn        int main(void)
 *  @brief      x
 *  @details    x
 *
 *  @param    [in]  (char *) name - x
 *
 *  @return   (int) x
 *
 *  @section    Opens
 *      Capture return value information
 */
/**************************************************************************************************/
int _unlink(char *name) {

	//Locals
	(void)name;

	errno = ENOENT;

	return -1;
}


/**************************************************************************************************/
/** @fcn        int _times(struct tms *buf)
 *  @brief      x
 *  @details    x
 *
 *  @param    [in]  (struct tms *) buf - x
 *
 *  @return   (int) x
 *
 *  @section    Opens
 *      Capture return value information
 */
/**************************************************************************************************/
int _times(struct tms *buf) {

	//Locals
	(void)buf;

	return -1;
}

/**************************************************************************************************/
/** @fcn        int _stat(char *file, struct stat *st)
 *  @brief      x
 *  @details    x
 *
 *  @param    [in]  (char *) file      - x
 *  @param    [in]  (struct stat *) st - x
 *
 *  @return   (int) x
 *
 *  @section    Opens
 *      Capture return value information
 */
/**************************************************************************************************/
int _stat(char *file, struct stat *st) {

	//Locals
	(void)file;

	st->st_mode = S_IFCHR;

	return 0;
}

/**************************************************************************************************/
/** @fcn        int _link(char *old, char *new)
 *  @brief      x
 *  @details    x
 *
 *  @param    [in]  (char *) old - x
 *  @param    [in]  (char *) new - x
 *
 *  @return   (int) x
 *
 *  @section    Opens
 *      Capture return value information
 */
/**************************************************************************************************/
int _link(char *old, char *new) {

	//Locals
	(void)old;
	(void)new;

	errno = EMLINK;

	return -1;
}

/**************************************************************************************************/
/** @fcn        int _fork(void)
 *  @brief      x
 *  @details    x
 *
 *  @return   (int) x
 *
 *  @section    Opens
 *      Capture return value information
 */
/**************************************************************************************************/
int _fork(void) {

	errno = EAGAIN;

	return -1;
}

/**************************************************************************************************/
/** @fcn        int _execve(char *name, char **argv, char **env)
 *  @brief      x
 *  @details    x
 *
 *  @param    [in]  (char *) name  - x
 *  @param    [in]  (char **) argv - x
 *  @param    [in]  (char **) env  - x
 *
 *  @return   (int) x
 *
 *  @section    Opens
 *      Capture return value information
 */
/**************************************************************************************************/
int _execve(char *name, char **argv, char **env) {

	//Locals
	(void)name;
	(void)argv;
	(void)env;

	errno = ENOMEM;

	return -1;
}
